language: php

php:
- '7.0'
- '7.1'
- '7.2'
- '7.3'
- '7.4'
- nightly
- '5.6'

addons:
  apt:
    packages:
    - python3

before_script:
- composer update
- "tests/install_deps.sh"

script:
- "tests/testing.php"
